### ISSUE TITLE
 Proxy error: Could not proxy request /api/products/?page=1 from localhost:3000 to http://localhost:9000

### ISSUE THREAD

**Issue by rkscodes** [dhatGuy/PERN-Store#16]
I am just trying to run this project first, but I get this error and product wouldn't load on the page, though I have not setup .env because there are lot of them and I have no idea which ones is required, but this error seems unrelated though.

**Comment by dhatGuy** [comment]
Most of the variables in the server's env file are needed. The api url and stripe secret key in the client's env file are important.
Can you setup the variables and tell me if it works?

**Comment by rkscodes** [comment]
Yeah actually I tried few things
1. I removed  "proxy": "http://localhost:9000" line from PERN-Store/client/package.json
2. Added a new file SetupProxy.js in Client folder
It resolved the proxy error though still no products were displayed on homepage. Here is a screenshot of products loading and console.
<img width="957" alt="image" src="https://user-images.githubusercontent.com/30290728/143656042-bf2db859-1d0e-452b-8563-0056eeb4e96e.png">
1.Then I tried to setup those variables but I see Postgress  and I am having hard time figuring it out, I have only used MongoDB, if you could give me some pointer on how to do it it would be great.
2.REACT_APP_API_URL in client env  I don't understand what to fill here.

**Comment by dhatGuy** [comment]
You might want to go through this [youtube tutorial](https://youtu.be/ldYcgPKEZC8) to get at least basic knowledge of postgresql.

**Comment by rkscodes** [comment]
Yeah thanks, got it now it working. But still NPM run build doesn't work it has same error. So, I have to both separate run on client and server folder and then it works fine.

**Comment by dhatGuy** [comment]
I'm currently AFK and for the next few weeks. I'll check the build script as soon as I'm back
